### ISSUE TITLE
SOZ : Mind flayer mind blast ignores immunities

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#13]
Ive been testing various effects to see if anything will block the stun effect from the mind flayer mind blast.

I read that the mind blast is considered a spell like ability, but protection from evil and lesser mind blank do not protect against it, despite clearly stating that they protect against mind affecting abilities.

I cant seem to find any spell that will protect you against the effect (at least, not the ones available for the CR of the encounter).

**Comment by kevL** [comment]
I'd like to look into it if/when i've got time ...

**Comment by Question2** [comment]
Is there anyone else who can do it atm?

**Comment by kevL** [comment]
anyone who can open the toolset

**Comment by Question2** [comment]
I found the problem in spells.2da....row 713, mindflayer_mindblast_10, has no immunities so will affect ANYTHING....row 714 has the same problem.

Row 716 is also missing mind immunity.

In total : rows 713, 714, 716, 789, 551, 693.

**Comment by kevL** [comment]
I'd like you to test an alternate spellscript for MindBlast, against the MindFlayers in the BlackMarket specifically (because i'm pretty confident they'll use this script...)

https://drive.google.com/file/d/1RFRtUPosyZAaXrNx3yb5zYTp6JSqb2M0/view?usp=sharing

\- unzip to \Override and check there's no other files named 'x2_m1_mindblast' in \Override

<br>
Notes:
The stock spellscript for SpellID #551 MONSTER_MindBlast 'x2_m1_mindblast' does not pass the caster into its SavingThrow check, so in theory it doesn't check the alignment of the caster against Protection from Alignment/Evil.<br><br>
This alternate spellscript does pass the caster into the SavingThrow check.

--
btw, the "ImmunityType" column in Spells.2da in Nwn2 has no hardcoded ramifications. It doesn't do anything (unless a custom script queries its value, so yes the entries should be kept consistent). Immunities, in Nwn2, are generally handled by the engine (ie, not in script).

**Comment by Question2** [comment]
I just tested protection from evil, lesser mind blank and skeleton warriors from animate dead. They all still get stunned by the mindblast. Your script is the only mindblast script in my override folder.

**Comment by Question2** [comment]
Heres the weird part...i just got to the zecorien fight, which uses the same mind blast. The alternate mindblast script message popups for both the underdark market and the zecorien fight...but for the zecorien fight, i had the staff of command equipped which grants mind immunity. And when zecorien hit me with the mind blast, i got a message saying that i was immune to mind affecting spells.

With lesser mind blank against the underdark market mind flayers, i never got the mind immunity message.

Maybe the staff of command just gives a special kind of mind immunity?

**Comment by kevL** [comment]
well, the staff is apparently granting immunity because it's an item ... I'll likely look into this more deeply when i have the time & inclination, since I want it fixed in my game too.

**Comment by kevL** [comment]
uh... i finally got around to checking ProtEvil vs. the MindFlayers in the BlackMarket and, with an Override that contains only Nwn2Fixes (everything else stock), my two chars who had ProtEvil buffs were immune to the MindBlasts – my other chars succumbed and had their brains extracted.
