### ISSUE TITLE
OC CK first visit

### ISSUE THREAD

**Issue by FerionVirian** [nwn2fixes/player#45]
when go through door to basement first time, after cut-scene PC teleported outside CK to starting point.
save before entering basement
https://drive.google.com/file/d/1AQCJXoXnMyVrFXw31P_nOpc5Pbu1AL9E/view?usp=sharing

**Comment by kevL** [comment]
this is strongly related to https://github.com/nwn2fixes/player/issues/44 I believe.

That is, the fix for that should be the fix for this -- although playthroughs that are in progess could be borked (a bit or more, unsure). Am currently looking into things more deeply, attempting to come to personal terms with the OC spaghetti ...

**Comment by kevL** [comment]
having looked into this a bit further (not comprehensively but still...) I think the fix for #44 resolves this issue also.

Unfortunately your playthrough is bugged, due to my previous oversight (re the 2330_cli_enter script). Sry

ps. i'm not sure how game-breaking that buggedness is ... if you wish to pursue it, please do so on the NeverwinterVault.org forums (since it's no longer a matter for Nwn2Fixes per se)

**Comment by FerionVirian** [comment]
did this affect playthrough before Ryte of Tyr? or it start with cutscene in CK basement?

**Comment by kevL** [comment]
playthrough up till the Ryte of Tyr (Trial By Combat vs Lorne, actually) ought be okay. The problem starts right after the TBC, because the PC gets warped into the CK basement to show the cutscene between Black Garius and Torio (the PC doesn't appear in the cutscene, but he/she has to be there for the cutscene to play). That's why your PC appeared in the CK basement ...

but the cutscene didn't play. Because the script that should have started the cutscene was being overridden by the script that initiates the battle between Black Garius and the PC-party along with the Many Starred Cloaks (Vale, Nathan, Sevann, etc.). This also happens in the CK basement ... but it's in a different module, and happens slightly later in the playthrough.

The designers of the OC recklessly kept the same filename for both scripts. So when i tweaked the latter script and placed it into /override, it overrode the first script also. Unfortunately, the content of those scripts is completely different, hence your current playthrough got bugged :\

If you're wondering where a good place to revert your playthough to, i suggest redoing the Trial By Combat w/ Khelgar vs Lorne. In fact i'd appreciate it if you did this, to test that the cutscene involving Black Garius and Torio starts okay after the arena. Then, slightly later, that the battle with the Many Starred Cloaks vs Black Garius starts okay.

note: There should also be a brief cutscene (also in the CK basement) that happens right after the 2nd battle with Qara's animus elemental, which shows Black Garius starting the ritual with the Shadow Priests. <- this is the ritual that your PC-party plus the Many Starred Cloaks are going to bust up.


lt.Danger, the Trial By Combat (also shows first cutscene in CK basement)
https://lparchive.org/Neverwinter-Nights-2/Update%2044/

lt.Danger, to Crossroad Keep (shows 2nd cutscene in CK basement, then busting up Black Garius' ritual)
https://lparchive.org/Neverwinter-Nights-2/Update%2050/

**Comment by FerionVirian** [comment]
Cutscene with Torio and Garius, after Trial, works now. PC teleports to sunken flagon.
Don't have Qara in party at all, so don't meet animus elemental. try to check this too.

**Comment by kevL** [comment]
sounds good so far ...

**Comment by FerionVirian** [comment]
a lot of time has passed. 
Cutscene with Garius ordering to start ritual begin on first CK visit. Qara's elemental second battle doesn't seem to affect cutscene. Cutscene begins without fight with elemental, after first fight, or after second fight. Same Cutscene every time, where Garius last sentence "we wouldn't want to keep Neverwinter waiting.
After Cutscene with Garius - party arrive to CK - dialog about dead man, dialog with Neverwinter enforcers.

**Comment by kevL** [comment]
so, everything seems okay for now?

**Comment by FerionVirian** [comment]
yes.
Completed CK conquest. Cutscenes in basement at the beginning of the fight and its end work well, cutscene with shadow reavers too.
