### ISSUE TITLE
Temporary CON buffs cause characters to take damage 

### ISSUE THREAD

**Issue by Question2** [nwn2fixes/player#7]
Temporary CON buffs via spells, items, polymorph, wildshape or other similar effects cause characters to take positive damage every time a new module is loaded or a savegame is loaded to drop them back to their base hp values. In the case of wildshape, I have seen Elanee in treat form take 100+ damage every time a savegame was loaded.

This hp damage shouldnt be permanent.

**Comment by kevL** [comment]
it's a known issue w/ Kaedrin's PrC Pack ...

will check out your other comments soon,

**Comment by Question2** [comment]
Oh, why that pack specifically?

Not sure if related but some NPCs also start out injured for no clear reason. Like, random towns people for example.

I also noticed that some spell effects seem to dissapear the moment you save the game. For example, if i cast greater magic fang on elanee while in wildshape form then save, the buff instantly dissapears.

**Comment by kevL** [comment]
> Oh, why that pack specifically?
because there's a hardcoded bug in the engine that increases a character's hitpoints when transitioning modules while wearing +Con gear. Kaedrin made a valiant attempt to fix it, but the dragon was just too big apparently.

> Not sure if related but some NPCs also start out injured for no clear reason.
(likely not related: ) designers/builders can set a creature's HP however they want (and the OC has injured NPCs walking around for whatever reason...)

> I also noticed that some spell effects seem to dissapear the moment you save the game. For example, if i cast greater magic fang on elanee while in wildshape form then save, the buff instantly dissapears.
hm. something to do with Polymorphing, maybe. I think the engine can't save a polymorphed creature as-is, so it quickly de-polys and re-polys the creature to make a save ... not sure.

I wouldn't be comfortable addressing any of those issues in 'Nwn2Fixes'. at least not at present

**Comment by Question2** [comment]
I remember reading somewhere that NWN2 uses a save system where companions are removed then re-added after saving, so saving the game causes companion casted effects to dissapear. I cant remember where i read that though...

Not sure what you mean by dragon too big?
